routes/admin.php
<?php

Route::group(['prefix'=>'admin'],function (){
    Config::set('auth.defines','admin');

//    login
    Route::get('/','Admin\AdminAuth@login')->name('admin.login');
    Route::post('adminlogin','Admin\AdminAuth@dologin');
    Route::get('forgetPassword','Admin\AdminAuth@forgetPassword');
    Route::post('forgetPassword','Admin\AdminAuth@forgetPasswordPost');
    Route::get('reset/password/{token}','Admin\AdminAuth@reset_password');
    Route::post('reset/password/{token}','Admin\AdminAuth@reset_password_post');




    Route::get('lang/{lang}',function ($lang){
        session()->has('lang')?session()->forget('lang'):'';
        $lang == 'ar' ? session()->put('lang','ar') : session()->put('lang','en');
        return back();
    });
//    admin panal
    Route::group(['middleware'=>'auth:admin'],function (){

        Route::get('/dashboard','DashboardController@home')->name('admin.home');
        Route::post('/sendmail','DashboardController@sendmail')->name('admin.sendmail');
        Route::any('logout','Admin\AdminAuth@a_logout');

//        admins
        Route::resource('admins','Admin\AdminController');
        Route::delete('admins/{id}','Admin\AdminController@destroy');


//        permission & role
        Route::resource('permissions','Admin\roles\PermissionController');
        Route::resource('roles','Admin\roles\RoleController');
        Route::resource('admins/permission_role','Admin\roles\permission_roles');
        //branches
        Route::resource('branches','Admin\Branches\BranchesController');
        Route::get('branchActive', 'Admin\Branches\BranchesController@branchActive')->name('branchActive'); 
//        setting
        Route::get('setting','SettingController@index')->name('setting');
        Route::post('setting','SettingController@setting_save')->name('setting.save');

        // features
        Route::get('setting/features','Admin\setting\FeaturesController@index')->name('features');
        Route::post('setting/features','Admin\setting\FeaturesController@features_save')->name('features.save');

        Route::resource('setting/homevideos','Admin\setting\HomeVideosController');
        Route::resource('setting/team','Admin\setting\teamController');


        Route::resource('setting/units', 'Admin\secondary\UnitsController');
        Route::resource('setting/wordlist', 'Admin\secondary\WordlistController');
        Route::get('wordlist_grammar', 'Admin\secondary\WordlistController@wordGrammar');


        Route::resource('slider', 'Admin\setting\SliderController');
        Route::resource('setting/content', 'Admin\secondary\ContentController');
        Route::resource('appointments', 'Admin\student\AppointmentController');
        Route::get('show_appointments', 'Admin\student\AppointmentController@show_appointments')->name('show_appointments');
        Route::get('show_exams', 'Admin\student\ExamsController@show_exams')->name('show_exams');
        Route::resource('exams', 'Admin\student\ExamsController');
        Route::resource('payments', 'Admin\student\PaymentsController');
        Route::get('getStudentPrice', 'Admin\student\PaymentsController@getStudentPrice')->name('getStudentPrice');

        Route::get('content_grammar', 'Admin\secondary\ContentController@content_grammar');

        // enlish gate EnglishListsController  EnglishListsContoller
        // english tree categories
        Route::resource('category', 'Admin\english\CategoryController');
        Route::get('deleteSubCat', 'Admin\english\CategoryController@deleteSubCat')->name('deleteSubCat');
        Route::get('editSubCat', 'Admin\english\CategoryController@editSubCat')->name('editSubCat');
        Route::get('getSubCategories', 'Admin\english\CategoryController@getSubCategories')->name('getSubCategories');
        Route::get('getSubCategoryChild', 'Admin\english\CategoryController@getSubCategoryChild')->name('getSubCategoryChild');
        Route::get('createTree','Admin\english\CategoryController@createTree')->name('createTree');
        Route::post('addContent','Admin\english\CategoryController@addContent')->name('addchildcatContent');
//        Route::get('category-tree-view/{id}','Admin\english\CategoryController@edit')->name('edit.category-tree-view');
//        Route::post('update-category','Admin\english\CategoryController@updateCategory')->name('category.update');

        Route::resource('englishlists', 'Admin\english\EnglishListsContoller');
        Route::resource('englishlistening', 'Admin\english\EnglishListeningController');
        Route::resource('englishwords', 'Admin\english\EnglishWordsController');
        Route::resource('englishgrammer', 'Admin\english\EnglishGrammersController');
        Route::get('english_content', 'Admin\english\EnglishGrammersController@english_content');

        Route::resource('englishdescription', 'Admin\english\EnglishDescriptionCntoller');

        // honor board
        Route::resource('honorboard','Admin\honorboard\HonorBoardController');

        // parents routes
        Route::resource('parents', 'Admin\parents\ParentsController');
        Route::get('parentActive', 'Admin\parents\ParentsController@parentActive')->name('parentActive');

        // library
        Route::resource('librarylists', 'Admin\library\LibraryListsContoller');
        // Route::resource('librarybooks','Admin\library\LibraryBooksController');
        // Route::get('library_content','Admin\library\LibraryBooksController@library_content');
        // add images or videos to library
        // Route::resource('librarymedia','Admin\library\LibraryImagesController');
        // Route::resource('libraryimages','Admin\pages\ImagesController');
        // Route::resource('libraryvideos','Admin\pages\VideosController');

         // pages
         Route::resource('images','Admin\pages\ImagesController');
         Route::resource('videos','Admin\pages\VideosController');
         Route::resource('resources','Admin\pages\ResourcesController');

         // homepage
         Route::resource('sayabout','Admin\pages\SayaboutController');
        //  Route::get('sayabout','Admin\pages\SayaboutController@index');
        //  Route::get('sayabout/{id}','Admin\pages\SayaboutController@destroy');
        Route::POST('sayabout','Admin\pages\SayaboutController@store')->name('sayabout.store');
         Route::get('sayabout/{id}/activate','Admin\pages\SayaboutController@isActive');


//        search
        Route::get('search', 'Admin\SearchController@index');



        Route::resource('posts','Admin\chat\PostsController');
        Route::resource('comments','Admin\chat\CommentsController');
          Route::Post('reply/{id}','Admin\chat\CommentsController@reply')->name('comments.reply');

        Route::resource('profile','Admin\profile\ProfileController');








        // customer
        Route::resource('students','Admin\student\studentController');
        Route::get('studentActive', 'Admin\student\studentController@studentActive')->name('studentActive');
        Route::resource('attendance','Admin\student\AttendancesController');

        Route::get('subbus','Admin\student\subbusController@index');
        Route::post('sub_student','Admin\student\subbusController@substudent');
        Route::post('sub_appointments','Admin\student\subbusController@subappointments');
        // Route::get('grades_data','Admin\student\studentController@grades_data')->name('grades_data');
        Route::post('sub_exams','Admin\student\subbusController@subexams');
        Route::get('remove_subparents/{parent_id}/{id}','Admin\student\subbusController@remove_subparents')->name('remove_subparents.destroy');
        Route::get('remove_subexam/{id}/{exam_id}','Admin\student\subbusController@remove_subexam')->name('remove_subexam.destroy');

        Route::resource('parents','Admin\parents\ParentsController');


//        employees
        Route::resource('employees','Admin\employees\EmployeeController');

//        blog
        Route::resource('blog','Admin\blog\BlogController');
        Route::resource('breaknews','Admin\blog\BreaknewController');

        //  departments
        Route::resource('departments','Admin\Department\DepartmentsController');
        Route::get('departments/department/print','Admin\Department\DepartmentsController@print');
        Route::get('departments/reports/report','Admin\Department\DepartmentsController@reports')->name('departments.reports');
        Route::get('departments/reports/details','Admin\Department\DepartmentsController@details')->name('departments.details');
        Route::post('departments/reports/pdf','Admin\Department\DepartmentsController@pdf');
//
        Route::get('departments/department/Review','Admin\Department\DepartmentsController@Review');
        Route::get('departments/department/reviewdepartment','Admin\Department\DepartmentsController@reviewdepartment')->name('reviewdepartment');
        Route::get('departments/{id}/show','Admin\Department\DepartmentsController@show_Department')->name('show_Department');


//
        //        cc
        Route::resource('cc','Admin\CC\CcController');
        Route::get('cc/report/motioncc','Admin\Cc\ReportController@motioncc');
        Route::get('cc/report/motioncc/show','Admin\Cc\ReportController@show');
        Route::get('cc/report/motioncc/details','Admin\Cc\ReportController@details');
        Route::get('cc/report/ccpublicbalance','Admin\Cc\ReportController@CCpublicbalance');
        Route::get('cc/report/ccpublicbalance/level','Admin\Cc\ReportController@CCpublicbalancelevel');
        Route::get('cc/report/ccpublicbalance/print','Admin\Cc\ReportController@CCpublicbalanceprint');
        Route::POST('cc/report/ccpublicbalance/pdf','Admin\Cc\ReportController@CCpublicbalancepdf');
        Route::post('cc/reports/pdf','Admin\Cc\ReportController@pdf');
        Route::get('cc/report/checkReports','Admin\Cc\ReportController@checkReports');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('lang/{lang}',function ($lang){
    session()->has('lang')?session()->forget('lang'):'';
    $lang == 'ar' ? session()->put('lang','ar') : session()->put('lang','en');
    return back();
});




Route::namespace('web')->group(function(){
    //  Route::get('/', function(){
    //      return view('web.index');
    //  });
    Route::get('/', 'HomeController@index')->name('home');
//    Route::get('showAppointments', 'WebController@showAppointments')->name('showAppointments');
    Route::get('showAppointments', 'HomeController@showAppointments')->name('showAppointments');
    Route::post('studentRegister','WebController@register')->name('studentRegister');
    Route::group(['middleware'=>'auth'],function (){
    //pages
    Route::get('/profile', 'HomeController@profile');
    Route::get('/video-gallery', 'HomeController@videogallery');
    Route::get('/onlinetest', 'HomeController@onlinetest');
    Route::get('/testnow', 'HomeController@testnow');
    // Route::get('/signin', 'HomeController@signin');
    Route::get('student_register','WebController@index')->name('student_register');


    Route::get('/sign-up-parents', 'HomeController@sign_up_parents');

    Route::post('parentRegister','WebController@parentRegister')->name('parentRegister');


    Route::get('getTree', 'HomeController@getTree')->name('getTree');
    Route::get('getTreeContent', 'HomeController@getTreeContent')->name('getTreeContent');
     Route::get('sayabout','WebController@sayabout');
     Route::POST('sayabout','WebController@sayabout_store')->name('sayabout.store');
    Route::get('/success_register', 'WebController@success_register');


    Route::get('/choose-your-group', 'HomeController@choose_your_group');
    Route::get('/photos-gallery', 'HomeController@photosgallery');
    Route::get('/references', 'HomeController@references');
    Route::get('/high-school-gate', 'HomeController@high_school_gate');
    Route::get('getGradeInfo', 'HomeController@getGradeInfo')->name('getGradeInfo');
    Route::get('/english-gate', 'HomeController@english_gate');

    Route::get('/sign-in-parents', 'HomeController@sign_in_parents');


    // Route::get('/', function(){
    //     return(view('web.pages.comming-soon.comming-soon'));
    // });

//    Route::get('/profile', 'ProfileController@index');

//	Route::get('/Secondary', 'SecondaryController@index');
//	Route::get('/honoboard/{id}/show', 'HonorBoardController@show')->name('honoboard.profile');
//
//    // chat
//    Route::get('/home', 'HomeController@chat')->name('home');
//
//    Route::get('/posts', 'chat\PostsController@index')->name('posts');
   Route::get('/posts', function(){
       return view('web.chat.index');
   });
//    Route::get('/post/show/{id}', 'chat\PostsController@show')->name('post.show');
//
//    Route::get('/post/create', 'chat\PostsController@create')->name('post.create');
//    Route::post('/post/store', 'chat\PostsController@store')->name('post.store');
//
//    Route::post('/comment/store', 'NestedCommentController@store')->name('comment.add');
//
//
//    Route::post('/reply/store', 'CommentController@replyStore')->name('reply.add');
//
//
//    Route::get('forum', 'ForumController@index');

Route::get('uploadfile', 'UploadController@create');
Route::post('upload', 'UploadController@upload');

// secondary
Route::get('/secgrade1/{id}', 'GatesController@show')->name('grade.show');

// Route::get('secgrade1', 'GatesController@index');


});
});




// ==========================

//mahmoud

//Route::resource('/studentLogin','WebstudentController' );
//Route::get('followstudents', 'WebstudentController@getlogin');

Route::get('forgetPassword','Auth\LoginController@forgetPassword');
Route::post('forgetPassword','Auth\LoginController@forgetPasswordPost')->name('reset_password');



Route::get('reset/password/{token}','Auth\LoginController@reset_password');
Route::post('reset/password/{token}','Auth\LoginController@reset_password_post')->name('resetpassword');
Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    // return what you want
});
Route::get('/route-cache', function() {
    $exitCode = Artisan::call('route:cache');
//    return '<h1>Routes cached</h1>';
});

//Clear Route cache:
Route::get('/route-clear', function() {
    $exitCode = Artisan::call('route:clear');
//    return '<h1>Route cache cleared</h1>';
});

//Clear View cache:
Route::get('/view-clear', function() {
    $exitCode = Artisan::call('view:clear');
//    return '<h1>View cache cleared</h1>';
});

//Clear Config cache:
Route::get('/config-cache', function() {
    $exitCode = Artisan::call('config:clear');
//    return '<h1>Clear Config cleared</h1>';
});

Route::get('/logout', function (){
    auth()->logout();
   
    return redirect('/');
});



//Route::get('student_register', function () {
//    return view('web/contact-us');
//});
//Route::resource('student_register','web\WebController');
//Route::POST('student_register','web\WebController@register');

Route::get('secgrade', function () {
    return view('web/Secondary-first-grade');
});

Route::get('gallery', function () {
    return view('web/gallery');
});

Route::get('videos', function () {
    return view('web/videos');
});

Route::get('resources', function () {
    return view('web/resources');
});

Route::get('books', function () {
    return view('web/books');
});

Route::get('engate', function () {
    return view('web/englishgate');
});

Route::get('chat', function () {
    return view('web/chat');
});

// =======================













// Route::get('followstudents', function () {
//     return view('web/WPF/followstudents');
// });





Route::get('exams', function () {
    return view('web/WPF/exams');
});

Route::get('timetable-age', function () {
    return view('web/WPF/timetable-age');
});

Route::get('timetable-nour', function () {
    return view('web/WPF/timetable-nour');
});



Route::get('news', function () {
    return view('web/WPF/news');
});

Route::get('contact', function () {
    return view('web/WPF/contact');
});




Auth::routes();

resources/views/admin/admins/create.blade.php
@extends('admin.index')
@section('title', trans('admin.Create_new_admin'))
@section('content')

<div class="box">
    @include('admin.layouts.message')
    <div class="box-header">
        <h3 class="box-title">{{$title}}</h3>
    </div>
    <div class="box-body">
        {!! Form::open(['method'=>'POST','route' => 'admins.store','files'=>true]) !!}
        <div class="form-group">
            {{ Form::label('admin.Branches', trans('admin.Branches') , ['class' => 'control-label']) }}
            {{ Form::select('branch_id', $branches,null, array_merge(['class' => 'form-control','placeholder'=>trans('admin.select')])) }}
        </div>
        <div class="form-group">
            {{ Form::label(trans('admin.name'), null, ['class' => 'control-label']) }}
            {{ Form::text('name', old('name'), array_merge(['class' => 'form-control'])) }}
        </div>
        <div class="form-group">
            {{ Form::label(trans('admin.email'), null, ['class' => 'control-label']) }}
            {{ Form::email('email', old('email'), array_merge(['class' => 'form-control'])) }}
        </div>
        <div class="form-group">
            {{ Form::label(trans('admin.password'), null, ['class' => 'control-label']) }}
            {{ Form::password('password', array_merge(['class' => 'form-control'])) }}
        </div>
        <div class="form-group">
            {{ Form::label(trans('admin.image'), null, ['class' => 'control-label']) }}
            {{ Form::file('image', array_merge(['class' => 'form-control'])) }}
        </div>
        {{Form::submit(trans('admin.save'),['class'=>'btn btn-primary'])}}
        <a href="{{aurl('admins')}}" class="btn btn-danger">{{trans('admin.back')}}</a>
{{--        <a href="{{ url()->previous() }}" class="btn btn-danger">Back</a>--}}
        {!! Form::close() !!}

    </div>
</div>
    

    <!-- <div class="alert alert-danger">{{trans('admin.you_cannt_see_invoice_because_you_dont_have_role_to_access')}}</div> -->

    







@endsection

resources/views/admin/admins/edit.blade.php
@extends('admin.index')
@section('title', trans('admin.Edit_admin'))
@section('content')
@hasrole('admin')
    <div class="box">
        @include('admin.layouts.message')
        <div class="box-header">
            <h3 class="box-title">{{$title}}</h3>
        </div>
        <div class="box-body">
            {!! Form::model($admin,['method'=>'PUT','route' => ['admins.update',$admin->id],'files'=>true]) !!}
            <div class="form-group">
                {{ Form::label('admin.Branches', trans('admin.Branches') , ['class' => 'control-label']) }}
                {{ Form::select('branches_id', $branches,$admin->branches_id, array_merge(['class' => 'form-control','placeholder'=>trans('admin.select')])) }}
            </div>
            <div class="form-group">
                {{ Form::label( trans('admin.name'), null, ['class' => 'control-label']) }}
                {{ Form::text('name', $admin->name, array_merge(['class' => 'form-control'])) }}
            </div>
            <div class="form-group">
                {{ Form::label( trans('admin.email'), null, ['class' => 'control-label']) }}
                {{ Form::email('email', $admin->email, array_merge(['class' => 'form-control'])) }}
            </div>
            <div class="form-group">
                {{ Form::label( trans('admin.password'), null, ['class' => 'control-label']) }}
                {{ Form::password('password', array_merge(['class' => 'form-control'])) }}
            </div>
            <div class="form-group">
                {{ Form::label( trans('admin.image'), null, ['class' => 'control-label']) }}
                {{ Form::file('image', array_merge(['class' => 'form-control'])) }}
                <img src="{{asset('storage/'.$admin->image)}}" style="width: 100px">
            </div>
            {{Form::submit( trans('admin.save'),['class'=>'btn btn-primary'])}}
            <a href="{{aurl('admins')}}" class="btn btn-danger">{{trans('admin.back')}}</a>
            {!! Form::close() !!}
        </div>
    </div>

@else
    <div class="alert alert-danger">{{trans('admin.you_cannt_see_invoice_because_you_dont_have_role_to_access')}}</div>

    @endhasrole






@endsection

resources/views/admin/admins/index.blade.php
@extends('admin.index')
@section('title',trans('admin.admin_datatable'))
@section('content')
    @hasrole('admin')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">{{trans('admin.admin_datatable')}} </h3>
        </div>
    @include('admin.layouts.message')
        <!-- /.box-header -->
        <div class="box-body table-responsive">
            {!! $dataTable->table([
             'class' => 'table table-bordered table-striped table-hover'
             ],true) !!}
        </div>
        <!-- /.box-body -->
    </div>







@push('js')
    {!! $dataTable->scripts() !!}
@endpush
    @else
        <div class="alert alert-danger">{{trans('admin.you_cannt_see_invoice_because_you_dont_have_role_to_access')}}</div>

        @endhasrole
@endsection

resources/views/admin/admins/per_role_edit.blade.php
@extends('admin.index')
@section('title',trans('admin.Edit_Permission'))
@section('content')
    @hasrole('admin')
    @push('js')
        <script>
            $(function () {
                'use strict'
                $('.type').select2({
                    placeholder: "Select...",
                    allowClear: true
                });
            });
        </script>


    @endpush
    @push('css')
        <style>
            .select2-container--default .select2-selection--multiple .select2-selection__choice{
                background-color: #333;
            }
        </style>

    @endpush
    <div class="box">
        @include('admin.layouts.message')
        <div class="box-header">
            <h3 class="box-title"> {{trans('admin.Edit_roles_and_permissions_of') . ' ' . $admin->name}}</h3>
        </div>
        <div class="box-body">
            {!! Form::model($admin->id,['method'=>'PUT','route' => ['permission_role.update',$admin->id]]) !!}
            <div class="form-group">
                {{ Form::label(trans('admin.Roles'), null, ['class' => 'control-label']) }}
                {!! Form::select('roles[]', $roles, $roles, ['multiple'=>'multiple','class' => 'form-control type']) !!}
            </div>
            <div class="form-group">
                {{ Form::label(trans('admin.permission'), null, ['class' => 'control-label']) }}
                {{Form::select('permissions[]',$permissions ,$permissions,array('multiple'=>'multiple','class' => 'form-control type'))}}
            </div>
            {{Form::submit(trans('admin.update'),['class'=>'btn btn-primary'])}}
            {!! Form::close() !!}
        </div>
    </div>

    @else
        <div class="alert alert-danger">{{trans('admin.you_cannt_see_invoice_because_you_dont_have_role_to_access')}}</div>

        @endhasrole






@endsection

resources/views/admin/admins/show.blade.php
@extends('admin.index')
@section('title',trans('admin.permission_Role'))
@section('content')
@hasrole('admin')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">{{trans('admin.permission_Role')}}</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive">
            <table id="show-table" class="table table-bordered table-hover text-center">
                <thead>
                    <tr>
                        <th>{{trans('admin.name')}}</th>
                        <th>{{trans('admin.Permissions')}}</th>
                        <th>{{trans('admin.Roles')}}</th>
                        <th>{{trans('admin.edit')}}</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{$admin->name}}</td>
                        <td>
                            @foreach($admin->permissions as $permission)
                                <span class="badge">{{$permission->name}}</span>
                            @endforeach
                        </td>
                        <td>
                            @foreach($admin->getRoleNames() as $role)
                                <span class="badge">{{$role}}</span>
                            @endforeach
                        </td>
                        <td><a href="{{route('permission_role.edit',$admin->id)}}" class="btn btn-success">{{trans('admin.edit')}}</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>


@else
    <div class="alert alert-danger">{{trans('admin.you_cannt_see_invoice_because_you_dont_have_role_to_access')}}</div>

    @endhasrole





@endsection